//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChangeApproverForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChangeApproverForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ChangeApproverForm", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Approver..
        /// </summary>
        internal static string Error_PendingWithWhom {
            get {
                return ResourceManager.GetString("Error_PendingWithWhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Replace By Whom..
        /// </summary>
        internal static string Error_ReplaceByWhom {
            get {
                return ResourceManager.GetString("Error_ReplaceByWhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Role Name..
        /// </summary>
        internal static string Error_RoleName {
            get {
                return ResourceManager.GetString("Error_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string Grid_Title_CreationDate {
            get {
                return ResourceManager.GetString("Grid_Title_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICDM No..
        /// </summary>
        internal static string Grid_Title_ICDMNo {
            get {
                return ResourceManager.GetString("Grid_Title_ICDMNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Status.
        /// </summary>
        internal static string Grid_Title_JobStatus {
            get {
                return ResourceManager.GetString("Grid_Title_JobStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver.
        /// </summary>
        internal static string Grid_Title_PendingWith {
            get {
                return ResourceManager.GetString("Grid_Title_PendingWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver.
        /// </summary>
        internal static string Grid_Title_PendingWithWhom {
            get {
                return ResourceManager.GetString("Grid_Title_PendingWithWhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared By.
        /// </summary>
        internal static string Grid_Title_PreparedBy {
            get {
                return ResourceManager.GetString("Grid_Title_PreparedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace By Whom.
        /// </summary>
        internal static string Grid_Title_ReplaceByWhom {
            get {
                return ResourceManager.GetString("Grid_Title_ReplaceByWhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string Grid_Title_RoleName {
            get {
                return ResourceManager.GetString("Grid_Title_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Grid_Title_Status {
            get {
                return ResourceManager.GetString("Grid_Title_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Approver.
        /// </summary>
        internal static string Label_ChangeApprover {
            get {
                return ResourceManager.GetString("Label_ChangeApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Staus:.
        /// </summary>
        internal static string Label_JobStatus {
            get {
                return ResourceManager.GetString("Label_JobStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Pending Request.
        /// </summary>
        internal static string Label_PendingRequest {
            get {
                return ResourceManager.GetString("Label_PendingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver:.
        /// </summary>
        internal static string Label_PendingWithWhom {
            get {
                return ResourceManager.GetString("Label_PendingWithWhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace By Whom:.
        /// </summary>
        internal static string Label_ReplaceByWhom {
            get {
                return ResourceManager.GetString("Label_ReplaceByWhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name:.
        /// </summary>
        internal static string Label_RoleName {
            get {
                return ResourceManager.GetString("Label_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Label_Search {
            get {
                return ResourceManager.GetString("Label_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Approver Master.
        /// </summary>
        internal static string Page_ICDMApprover_Title {
            get {
                return ResourceManager.GetString("Page_ICDMApprover_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver Replacement List.
        /// </summary>
        internal static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Approver Replacement.
        /// </summary>
        internal static string Popup_Title_Addapproverreplacement {
            get {
                return ResourceManager.GetString("Popup_Title_Addapproverreplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Approver Replacement.
        /// </summary>
        internal static string Popup_Title_Editapproverreplacement {
            get {
                return ResourceManager.GetString("Popup_Title_Editapproverreplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Deleted Successfully..
        /// </summary>
        internal static string Text_ApproverReplacementDeleted {
            get {
                return ResourceManager.GetString("Text_ApproverReplacementDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record is not Deleted Successfully..
        /// </summary>
        internal static string Text_ApproverReplacementNotDeleted {
            get {
                return ResourceManager.GetString("Text_ApproverReplacementNotDeleted", resourceCulture);
            }
        }
    }
}
