//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ICCPForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ICCPForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ICCPForm", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment for ADS Required..
        /// </summary>
        internal static string Error_ADSAttachment {
            get {
                return ResourceManager.GetString("Error_ADSAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select BIS Registration Applicable..
        /// </summary>
        internal static string Error_BISRegistrationApplicable {
            get {
                return ResourceManager.GetString("Error_BISRegistrationApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter BM Lead Time (Days)..
        /// </summary>
        internal static string Error_BMLeadTime {
            get {
                return ResourceManager.GetString("Error_BMLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment for BOM Required..
        /// </summary>
        internal static string Error_BOMAttachment {
            get {
                return ResourceManager.GetString("Error_BOMAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Buy/Make..
        /// </summary>
        internal static string Error_BuyMake {
            get {
                return ResourceManager.GetString("Error_BuyMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Confirmed Order from Customer..
        /// </summary>
        internal static string Error_ConfirmedOrderFromCustomer {
            get {
                return ResourceManager.GetString("Error_ConfirmedOrderFromCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Costing Delegate User..
        /// </summary>
        internal static string Error_CostingDelegate {
            get {
                return ResourceManager.GetString("Error_CostingDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Item Code Creator(ICC) User..
        /// </summary>
        internal static string Error_CostingDelegate2 {
            get {
                return ResourceManager.GetString("Error_CostingDelegate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Cost Price..
        /// </summary>
        internal static string Error_CostPrice {
            get {
                return ResourceManager.GetString("Error_CostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Currency..
        /// </summary>
        internal static string Error_Currency {
            get {
                return ResourceManager.GetString("Error_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Implementation is Required..
        /// </summary>
        internal static string Error_DateOfImplementation {
            get {
                return ResourceManager.GetString("Error_DateOfImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Component Stock is Required..
        /// </summary>
        internal static string Error_ExistingComponentStock {
            get {
                return ResourceManager.GetString("Error_ExistingComponentStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FG Stock is Required..
        /// </summary>
        internal static string Error_FGStock {
            get {
                return ResourceManager.GetString("Error_FGStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Final SMS Delegate User..
        /// </summary>
        internal static string Error_FinalSMSDelegate {
            get {
                return ResourceManager.GetString("Error_FinalSMSDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter GST Rate (%)..
        /// </summary>
        internal static string Error_GSTRate {
            get {
                return ResourceManager.GetString("Error_GSTRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter HSN Code..
        /// </summary>
        internal static string Error_HSNCode {
            get {
                return ResourceManager.GetString("Error_HSNCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment for IES File Required..
        /// </summary>
        internal static string Error_IESFileAttachment {
            get {
                return ResourceManager.GetString("Error_IESFileAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Joint Inspection..
        /// </summary>
        internal static string Error_IsJointInspectionDone {
            get {
                return ResourceManager.GetString("Error_IsJointInspectionDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Item Code..
        /// </summary>
        internal static string Error_ItemCode {
            get {
                return ResourceManager.GetString("Error_ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Item Description..
        /// </summary>
        internal static string Error_ItemDescription {
            get {
                return ResourceManager.GetString("Error_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment for Joint Inspection is Required..
        /// </summary>
        internal static string Error_JointInspectionAttachment {
            get {
                return ResourceManager.GetString("Error_JointInspectionAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment for LM79 Required..
        /// </summary>
        internal static string Error_LM79Attachment {
            get {
                return ResourceManager.GetString("Error_LM79Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select LUM Marketing Delegate User..
        /// </summary>
        internal static string Error_LUMMarketingDelegate {
            get {
                return ResourceManager.GetString("Error_LUMMarketingDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment for Packaging Data Sheet Required..
        /// </summary>
        internal static string Error_PackagingDataSheetAttachment {
            get {
                return ResourceManager.GetString("Error_PackagingDataSheetAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Pilot Lot Preparation..
        /// </summary>
        internal static string Error_PilotLotPreparation {
            get {
                return ResourceManager.GetString("Error_PilotLotPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Product Group..
        /// </summary>
        internal static string Error_ProductGroup {
            get {
                return ResourceManager.GetString("Error_ProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select QA Delegate User..
        /// </summary>
        internal static string Error_QADelegate {
            get {
                return ResourceManager.GetString("Error_QADelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Quantity..
        /// </summary>
        internal static string Error_Quantity {
            get {
                return ResourceManager.GetString("Error_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment for Reliability Test Report is Required..
        /// </summary>
        internal static string Error_ReliabilityTestReportAttachment {
            get {
                return ResourceManager.GetString("Error_ReliabilityTestReportAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter RM Lead Time (Days)..
        /// </summary>
        internal static string Error_RMLeadTime {
            get {
                return ResourceManager.GetString("Error_RMLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter R Number/Application Number..
        /// </summary>
        internal static string Error_RNumber {
            get {
                return ResourceManager.GetString("Error_RNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select LUM Design Delegate User..
        /// </summary>
        internal static string Error_SCMLUMDesignDelegate {
            get {
                return ResourceManager.GetString("Error_SCMLUMDesignDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select SMS Delegate User..
        /// </summary>
        internal static string Error_SMSDelegate {
            get {
                return ResourceManager.GetString("Error_SMSDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment for Specification Sheet Required..
        /// </summary>
        internal static string Error_SpecificationSheetAttachment {
            get {
                return ResourceManager.GetString("Error_SpecificationSheetAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Vendor(s)..
        /// </summary>
        internal static string Error_tblVendors {
            get {
                return ResourceManager.GetString("Error_tblVendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment for TDS is Required..
        /// </summary>
        internal static string Error_TDSAttachment {
            get {
                return ResourceManager.GetString("Error_TDSAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select TDS Delegate User..
        /// </summary>
        internal static string Error_TDSDelegate {
            get {
                return ResourceManager.GetString("Error_TDSDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Packaging Type Required..
        /// </summary>
        internal static string Error_TypeOfPackaging {
            get {
                return ResourceManager.GetString("Error_TypeOfPackaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name is Required..
        /// </summary>
        internal static string Error_VendorName {
            get {
                return ResourceManager.GetString("Error_VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Vendor(s)..
        /// </summary>
        internal static string Error_Vendors {
            get {
                return ResourceManager.GetString("Error_Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Warranty..
        /// </summary>
        internal static string Error_Warranty {
            get {
                return ResourceManager.GetString("Error_Warranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Warranty..
        /// </summary>
        internal static string Errro_Warranty {
            get {
                return ResourceManager.GetString("Errro_Warranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Vendor Data Selected..
        /// </summary>
        internal static string Grid_Text_NoVendorData {
            get {
                return ResourceManager.GetString("Grid_Text_NoVendorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Implementation.
        /// </summary>
        internal static string Grid_Title_DateOfImplementation {
            get {
                return ResourceManager.GetString("Grid_Title_DateOfImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Goods Stock at Warehouse.
        /// </summary>
        internal static string Grid_Title_ExistingComponentStock {
            get {
                return ResourceManager.GetString("Grid_Title_ExistingComponentStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Goods Stock.
        /// </summary>
        internal static string Grid_Title_FGStock {
            get {
                return ResourceManager.GetString("Grid_Title_FGStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name.
        /// </summary>
        internal static string Grid_Title_VendorName {
            get {
                return ResourceManager.GetString("Grid_Title_VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload ADS:.
        /// </summary>
        internal static string Label_ADSAttachment {
            get {
                return ResourceManager.GetString("Label_ADSAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIS Registration Applicable:.
        /// </summary>
        internal static string Label_BISRegistrationApplicable {
            get {
                return ResourceManager.GetString("Label_BISRegistrationApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BM Lead Time (Days):.
        /// </summary>
        internal static string Label_BMLeadTime {
            get {
                return ResourceManager.GetString("Label_BMLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload BOM:.
        /// </summary>
        internal static string Label_BOMAttachment {
            get {
                return ResourceManager.GetString("Label_BOMAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy/Make:.
        /// </summary>
        internal static string Label_BuyMake {
            get {
                return ResourceManager.GetString("Label_BuyMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed Order from Customer:.
        /// </summary>
        internal static string Label_ConfirmedOrderFromCustomer {
            get {
                return ResourceManager.GetString("Label_ConfirmedOrderFromCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costing Delegate User:.
        /// </summary>
        internal static string Label_CostingDelegate {
            get {
                return ResourceManager.GetString("Label_CostingDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code Creator(ICC):.
        /// </summary>
        internal static string Label_CostingDelegate2 {
            get {
                return ResourceManager.GetString("Label_CostingDelegate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Price:.
        /// </summary>
        internal static string Label_CostPrice {
            get {
                return ResourceManager.GetString("Label_CostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation Date:.
        /// </summary>
        internal static string Label_DateOfImplementation {
            get {
                return ResourceManager.GetString("Label_DateOfImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Component Stock :.
        /// </summary>
        internal static string Label_ExistingComponentStock {
            get {
                return ResourceManager.GetString("Label_ExistingComponentStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Annual Business Volume (Nos):.
        /// </summary>
        internal static string Label_ExpectedAnnualBusinessVolume {
            get {
                return ResourceManager.GetString("Label_ExpectedAnnualBusinessVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FG Stock:.
        /// </summary>
        internal static string Label_FGStock {
            get {
                return ResourceManager.GetString("Label_FGStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final SMS Delegate User:.
        /// </summary>
        internal static string Label_FinalSMSDelegate {
            get {
                return ResourceManager.GetString("Label_FinalSMSDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Rate (%):.
        /// </summary>
        internal static string Label_GSTRate {
            get {
                return ResourceManager.GetString("Label_GSTRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSN Code:.
        /// </summary>
        internal static string Label_HSNCode {
            get {
                return ResourceManager.GetString("Label_HSNCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICDM Request No.:.
        /// </summary>
        internal static string Label_ICCPNo {
            get {
                return ResourceManager.GetString("Label_ICCPNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload IES File:.
        /// </summary>
        internal static string Label_IESFileAttachment {
            get {
                return ResourceManager.GetString("Label_IESFileAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is ICDM Retrieved?.
        /// </summary>
        internal static string Label_IsICCPRetrieved {
            get {
                return ResourceManager.GetString("Label_IsICCPRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Joint Inspection Done?.
        /// </summary>
        internal static string Label_IsJointInspectionDone {
            get {
                return ResourceManager.GetString("Label_IsJointInspectionDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code:.
        /// </summary>
        internal static string Label_ItemCode {
            get {
                return ResourceManager.GetString("Label_ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description:.
        /// </summary>
        internal static string Label_ItemDescription {
            get {
                return ResourceManager.GetString("Label_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item To Be Phased Out With Effect From:.
        /// </summary>
        internal static string Label_ItemPhasedOutWithEffectFrom {
            get {
                return ResourceManager.GetString("Label_ItemPhasedOutWithEffectFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item To Be Phased Out:.
        /// </summary>
        internal static string Label_ItemToBePhasedOut {
            get {
                return ResourceManager.GetString("Label_ItemToBePhasedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Joint Inspection File:.
        /// </summary>
        internal static string Label_JointInspectionAttachment {
            get {
                return ResourceManager.GetString("Label_JointInspectionAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload LM79:.
        /// </summary>
        internal static string Label_LM79Attachment {
            get {
                return ResourceManager.GetString("Label_LM79Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUM Marketing Delegate User:.
        /// </summary>
        internal static string Label_LUMMarketingDelegate {
            get {
                return ResourceManager.GetString("Label_LUMMarketingDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old ICDM Request Created Date:.
        /// </summary>
        internal static string Label_OldICCPCreatedDate {
            get {
                return ResourceManager.GetString("Label_OldICCPCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old ICDM Request No.:.
        /// </summary>
        internal static string Label_OldICCPNo {
            get {
                return ResourceManager.GetString("Label_OldICCPNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old ICDM Request Rejected Date:.
        /// </summary>
        internal static string Label_OldICCPRejectedDate {
            get {
                return ResourceManager.GetString("Label_OldICCPRejectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Packaging Data Sheet:.
        /// </summary>
        internal static string Label_PackagingDataSheetAttachment {
            get {
                return ResourceManager.GetString("Label_PackagingDataSheetAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilot Lot Preparation:.
        /// </summary>
        internal static string Label_PilotLotPreparation {
            get {
                return ResourceManager.GetString("Label_PilotLotPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Product Drawing(s):.
        /// </summary>
        internal static string Label_ProductDrawingAttachment {
            get {
                return ResourceManager.GetString("Label_ProductDrawingAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group:.
        /// </summary>
        internal static string Label_ProductGroup {
            get {
                return ResourceManager.GetString("Label_ProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed By:.
        /// </summary>
        internal static string Label_ProposedBy {
            get {
                return ResourceManager.GetString("Label_ProposedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA Delegate User:.
        /// </summary>
        internal static string Label_QADelegate {
            get {
                return ResourceManager.GetString("Label_QADelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        internal static string Label_Quantity {
            get {
                return ResourceManager.GetString("Label_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Product:.
        /// </summary>
        internal static string Label_ReferenceProduct {
            get {
                return ResourceManager.GetString("Label_ReferenceProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Reliability Test Report:.
        /// </summary>
        internal static string Label_ReliabilityTestReportAttachment {
            get {
                return ResourceManager.GetString("Label_ReliabilityTestReportAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date:.
        /// </summary>
        internal static string Label_RequestDate {
            get {
                return ResourceManager.GetString("Label_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM Lead Time (Days):.
        /// </summary>
        internal static string Label_RMLeadTime {
            get {
                return ResourceManager.GetString("Label_RMLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R Number/Application Number:.
        /// </summary>
        internal static string Label_RNumber {
            get {
                return ResourceManager.GetString("Label_RNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUM Design Delegate User:.
        /// </summary>
        internal static string Label_SCMLUMDesignDelegate {
            get {
                return ResourceManager.GetString("Label_SCMLUMDesignDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Delegate User:.
        /// </summary>
        internal static string Label_SMSDelegate {
            get {
                return ResourceManager.GetString("Label_SMSDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Specification Sheet:.
        /// </summary>
        internal static string Label_SpecificationSheetAttachment {
            get {
                return ResourceManager.GetString("Label_SpecificationSheetAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload TDS:.
        /// </summary>
        internal static string Label_TDSAttachment {
            get {
                return ResourceManager.GetString("Label_TDSAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDS Delegate User:.
        /// </summary>
        internal static string Label_TDSDelegate {
            get {
                return ResourceManager.GetString("Label_TDSDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging Type Required:.
        /// </summary>
        internal static string Label_TypeOfPackaging {
            get {
                return ResourceManager.GetString("Label_TypeOfPackaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Artwork:.
        /// </summary>
        internal static string Label_UploadArtworkAttachment {
            get {
                return ResourceManager.GetString("Label_UploadArtworkAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name:.
        /// </summary>
        internal static string Label_VendorName {
            get {
                return ResourceManager.GetString("Label_VendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor(s):.
        /// </summary>
        internal static string Label_Vendors {
            get {
                return ResourceManager.GetString("Label_Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty:.
        /// </summary>
        internal static string Label_Warranty {
            get {
                return ResourceManager.GetString("Label_Warranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code Creation Pre-Process.
        /// </summary>
        internal static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vendor.
        /// </summary>
        internal static string Popup_Title_AddVendor {
            get {
                return ResourceManager.GetString("Popup_Title_AddVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Vendor.
        /// </summary>
        internal static string Popup_Title_EditVendor {
            get {
                return ResourceManager.GetString("Popup_Title_EditVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costing Delegate Section.
        /// </summary>
        internal static string Section_Title_CostingDelegate1Section {
            get {
                return ResourceManager.GetString("Section_Title_CostingDelegate1Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code Creator(ICC).
        /// </summary>
        internal static string Section_Title_CostingDelegate2Section {
            get {
                return ResourceManager.GetString("Section_Title_CostingDelegate2Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costing Incharge Section.
        /// </summary>
        internal static string Section_Title_CostingInchargeSection {
            get {
                return ResourceManager.GetString("Section_Title_CostingInchargeSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final SMS Delegate Section.
        /// </summary>
        internal static string Section_Title_FinalSMSDelegateSection {
            get {
                return ResourceManager.GetString("Section_Title_FinalSMSDelegateSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final SMS Incharge Section.
        /// </summary>
        internal static string Section_Title_FinalSMSInchargeSection {
            get {
                return ResourceManager.GetString("Section_Title_FinalSMSInchargeSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUM Marketing Delegate Section.
        /// </summary>
        internal static string Section_Title_LUMmktDelegateSection {
            get {
                return ResourceManager.GetString("Section_Title_LUMmktDelegateSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUM Marketing Incharge Section.
        /// </summary>
        internal static string Section_Title_LUMmktInchargeSection {
            get {
                return ResourceManager.GetString("Section_Title_LUMmktInchargeSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA Delegate Section.
        /// </summary>
        internal static string Section_Title_QADelegateSection {
            get {
                return ResourceManager.GetString("Section_Title_QADelegateSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA Incharge Section.
        /// </summary>
        internal static string Section_Title_QAInchargeSection {
            get {
                return ResourceManager.GetString("Section_Title_QAInchargeSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUM Design Delegate Section.
        /// </summary>
        internal static string Section_Title_SCMLUMDesignDelegateSection {
            get {
                return ResourceManager.GetString("Section_Title_SCMLUMDesignDelegateSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUM Design Incharge Section.
        /// </summary>
        internal static string Section_Title_SCMLUMDesignInchargeSection {
            get {
                return ResourceManager.GetString("Section_Title_SCMLUMDesignInchargeSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Delegate Section.
        /// </summary>
        internal static string Section_Title_SMSDelegateSection {
            get {
                return ResourceManager.GetString("Section_Title_SMSDelegateSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Incharge Section.
        /// </summary>
        internal static string Section_Title_SMSInchargeSection {
            get {
                return ResourceManager.GetString("Section_Title_SMSInchargeSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDS Delegate Section.
        /// </summary>
        internal static string Section_Title_TDSDelegateSection {
            get {
                return ResourceManager.GetString("Section_Title_TDSDelegateSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDS Incharge Section.
        /// </summary>
        internal static string Section_Title_TDSInchargeSection {
            get {
                return ResourceManager.GetString("Section_Title_TDSInchargeSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can approve this request by clicking on Confirm button..
        /// </summary>
        internal static string Show_Confirm_Button {
            get {
                return ResourceManager.GetString("Show_Confirm_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code Creation Preprocess Request is Completed Successfully..
        /// </summary>
        internal static string Text_CompleteSuccess {
            get {
                return ResourceManager.GetString("Text_CompleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code Creation Preprocess Request Delegated Successfully..
        /// </summary>
        internal static string Text_DelegatedSuccess {
            get {
                return ResourceManager.GetString("Text_DelegatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code Creation Preprocess Request is On Hold..
        /// </summary>
        internal static string Text_HoldSuccess {
            get {
                return ResourceManager.GetString("Text_HoldSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code Creation Preprocess Request is Rejected Successfully..
        /// </summary>
        internal static string Text_RejectedSuccess {
            get {
                return ResourceManager.GetString("Text_RejectedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code Creation Preprocess Request  is Resume Successfully..
        /// </summary>
        internal static string Text_ResumeSuccess {
            get {
                return ResourceManager.GetString("Text_ResumeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code Creation Preprocess Request is Sent Back for Rework..
        /// </summary>
        internal static string Text_Rework {
            get {
                return ResourceManager.GetString("Text_Rework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code Creation Preprocess Request Save as Draft Successfully..
        /// </summary>
        internal static string Text_SaveDraftSuccess {
            get {
                return ResourceManager.GetString("Text_SaveDraftSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code Creation Preprocess Request Saved Successfully..
        /// </summary>
        internal static string Text_SaveSuccess {
            get {
                return ResourceManager.GetString("Text_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code Creation Preprocess Request is Submitted Successfully..
        /// </summary>
        internal static string Text_Success {
            get {
                return ResourceManager.GetString("Text_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This vendor Name is Already Exists..
        /// </summary>
        internal static string Text_UniqeVendor {
            get {
                return ResourceManager.GetString("Text_UniqeVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Details Deleted Successfully..
        /// </summary>
        internal static string Text_VendorDeleted {
            get {
                return ResourceManager.GetString("Text_VendorDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast One Vendor Detail is Required..
        /// </summary>
        internal static string Text_VendorRequired {
            get {
                return ResourceManager.GetString("Text_VendorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Details Saved Successfully..
        /// </summary>
        internal static string Text_VendorSave {
            get {
                return ResourceManager.GetString("Text_VendorSave", resourceCulture);
            }
        }
    }
}
