//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Report {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Report() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Report", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select From Date..
        /// </summary>
        internal static string Error_FromDate {
            get {
                return ResourceManager.GetString("Error_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select To Date..
        /// </summary>
        internal static string Error_ToDate {
            get {
                return ResourceManager.GetString("Error_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy / Make.
        /// </summary>
        internal static string Grid_BuyMake {
            get {
                return ResourceManager.GetString("Grid_BuyMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Price.
        /// </summary>
        internal static string Grid_CostPrice {
            get {
                return ResourceManager.GetString("Grid_CostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string Grid_CreatedBy {
            get {
                return ResourceManager.GetString("Grid_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string Grid_CreatedDate {
            get {
                return ResourceManager.GetString("Grid_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Rate.
        /// </summary>
        internal static string Grid_GSTRate {
            get {
                return ResourceManager.GetString("Grid_GSTRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICDM No..
        /// </summary>
        internal static string Grid_ICCPNo {
            get {
                return ResourceManager.GetString("Grid_ICCPNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICDM No..
        /// </summary>
        internal static string Grid_ICDMNo {
            get {
                return ResourceManager.GetString("Grid_ICDMNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        internal static string Grid_ItemCode {
            get {
                return ResourceManager.GetString("Grid_ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description.
        /// </summary>
        internal static string Grid_ItemDescription {
            get {
                return ResourceManager.GetString("Grid_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending With.
        /// </summary>
        internal static string Grid_PendingWith {
            get {
                return ResourceManager.GetString("Grid_PendingWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group.
        /// </summary>
        internal static string Grid_ProductGroup {
            get {
                return ResourceManager.GetString("Grid_ProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Grid_Quantity {
            get {
                return ResourceManager.GetString("Grid_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Grid_Status {
            get {
                return ResourceManager.GetString("Grid_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging Type.
        /// </summary>
        internal static string Grid_TypeofPackaging {
            get {
                return ResourceManager.GetString("Grid_TypeofPackaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty.
        /// </summary>
        internal static string Grid_Warranty {
            get {
                return ResourceManager.GetString("Grid_Warranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        internal static string Label_ExportToExcel {
            get {
                return ResourceManager.GetString("Label_ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date :.
        /// </summary>
        internal static string Label_FromDate {
            get {
                return ResourceManager.GetString("Label_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending With :.
        /// </summary>
        internal static string Label_PendingWith {
            get {
                return ResourceManager.GetString("Label_PendingWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Label_Search {
            get {
                return ResourceManager.GetString("Label_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status :.
        /// </summary>
        internal static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date :.
        /// </summary>
        internal static string Label_ToDate {
            get {
                return ResourceManager.GetString("Label_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICDM Date wise Report.
        /// </summary>
        internal static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
    }
}
